# Generated by Django 3.2.15 on 2022-09-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasmowebsite', '0002_porbblue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueShark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, verbose_name='Scientific Name')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('date', models.DateField(auto_now=True, verbose_name='Date Collected')),
                ('collector', models.CharField(max_length=255, verbose_name='Collector')),
                ('locality', models.CharField(max_length=255, verbose_name='Locality')),
                ('sex', models.CharField(max_length=255, verbose_name='Sex')),
                ('life_stage', models.CharField(max_length=255, verbose_name='Life Stage')),
                ('weight_kg', models.FloatField(verbose_name='Weight')),
                ('length_meters', models.FloatField(verbose_name='Length')),
                ('common_name', models.CharField(max_length=255, verbose_name='Common Name')),
            ],
        ),
        migrations.CreateModel(
            name='Zambezi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, verbose_name='Scientific Name')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('date', models.DateField(auto_now=True, verbose_name='Date Collected')),
                ('collector', models.CharField(max_length=255, verbose_name='Collector')),
                ('locality', models.CharField(max_length=255, verbose_name='Locality')),
                ('common_name', models.CharField(max_length=255, verbose_name='Common Name')),
            ],
        ),
    ]
